---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: all-in-one
    run_list:
      - recipe[chef-solo-search::default]
      - recipe[capistrano-wordpress::all-in-one-role]
    attributes:
