AllCops:
  Exclude:
    - 'Gemfile'
    - 'metadata.rb'
    - '.kitchen/*'
    - 'spec/fixtures/**/*'
    - 'Berksfile*'

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 50

Documentation:
  Enabled:
    false
