name             'capistrano-wordpress'
maintainer       'Adam Krone'
maintainer_email 'krone.adam@gmail.com'
license          'Apache v2.0'
description      'Installs/Configures capistrano-wordpress'
long_description 'Installs/Configures capistrano-wordpress'
version          '0.3.0'

depends 'apt'
depends 'users'
depends 'sudo'
depends 'ssh-hardening'
depends 'nodejs'
depends 'php'
depends 'composer'
depends 'capistrano-base'
depends 'apache2'
